apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vcsim-server
  namespace: openfaas
  labels:
    app: vcsim
    component: vcsim-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vcsim
        component: vcsim-server
    spec:
      containers:
      - name: vcsim
        image: embano1/vcsim:e560c7b
        command: ["./vcsim"]
        args: ["-tls=false", "-httptest.serve", ":8989"]
        ports:
        - containerPort: 8989
