[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/openfaas-incubator/connector-sdk"
  version = "0.2.0"

[[constraint]]
  name = "github.com/vmware/govmomi"
  version = "0.19.0"

[[constraint]]
  name = "github.com/openfaas/openfaas-cloud"
  version = "0.9.4"
